name: generators
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.0
  source_gen: ^1.3.1
  flutter_inappwebview_internal_annotations: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.2
  build_test: ^2.1.7
  test: ^1.24.2