name: flutter_inappwebview_internal_annotations
description: Internal annotations used by the generator of flutter_inappwebview plugin
version: 1.1.0
homepage: https://github.com/pichillilorenzo/flutter_inappwebview

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  test: ^1.21.6